### ISSUE TITLE
Improve Documentation around supported Kernel versions 

### ISSUE THREAD

**Issue by cpu6660** [google/fscrypt#117]
![image](https://user-images.githubusercontent.com/13901890/50469390-22f3a900-09e7-11e9-9b71-ffc7f76094ee.png)
@kant @wjt @cdibona @ilius

**Comment by josephlr** [comment]
@wjt, you're entirely correct. Ext4 has only supported encryption since version 4.1 (and this feature was not backported to impervious kernel versions).

@cpu6660 I've updated the title of this issue to empsizes that this is a documentation issue. We need to make it clear that:
- `fscrypt` cannot work with EXT4 on versions prior to 4.1
- Users should be careful when encrypting removable media that might be attached to older systems.

PS: Tagging cdibona on issues won't usually do anything. He's here for legal compliance. Tag me for anything technical.
