### ISSUE TITLE
Should the keys be 32 bytes or 64 bytes?

### ISSUE THREAD

**Issue by obadz** [google/fscrypt#121]
According to https://www.kernel.org/doc/html/v4.18/filesystems/fscrypt.html, the master key should be 64 bytes.

According to https://github.com/google/fscrypt/blob/master/README.md, it should be 32 bytes.

Which one is right?

**Comment by ebiggers** [comment]
Both are correct as they are referring to different keys.  The kernel documentation is only concerned with the key that gets actually passed to the kernel, which the fscrypt program calls the "policy key".  On the other hand, the 32-byte keys discussed in the fscrypt program's documentation for "raw key protectors" are "protector keys".  Each protector can wrap one or more "encryption policies".  This allows you to change the protector that protects an encrypted directory, e.g. change the passphrase, without having to re-encrypt the entire directory.

**Comment by josephlr** [comment]
@ebiggers is exactly correct here. The lengths are defined in [constants.go](https://github.com/google/fscrypt/blob/509bb4d450cdd923bf09d05a5622cb6e98646bce/metadata/constants.go#L30-L33) where the distinction between "internal keys" and "policy keys" is made.

@obadz I'm closing this, but we will probobly improve the documentation in the future to prevent this type of confusion (perhaps a "details" section of the wiki).

**Comment by obadz** [comment]
Is the 64 byte key derived from the 32 byte key and if so, why sacrifice the entropy?

**Comment by ebiggers** [comment]
Not quite; both types of key are randomly generated, and protector keys are used to wrap policy keys using AES-256-CTR and HMAC-SHA256, where the AES-256-CTR and HMAC-SHA256 keys are derived from the protector keys using HKDF-SHA256.  The IV for AES-256-CTR is randomly generated.

As for why the policy key is 64 bytes rather than 32, it's mostly a quirk of the kernel interface.  The kernel currently uses a length-preserving KDF to derive the actual per-file keys, which for AES-256-XTS are 64 bytes because of a quirk of the XTS specification.  But no cipher supported by fscrypt, including AES-256-XTS, actually has a _security level_ greater than 256 bits.  256-bit symmetric encryption is state of the art. 
 So, a 256-bit wrapping key is perfectly sufficient, provided that it is generated uniformly at random.

FYI, it may be helpful to read the design document for the fscrypt program: https://goo.gl/55cCrI

**Comment by obadz** [comment]
I see, thank @ebiggers & @josephlr.

I was hoping to store my keys in `pass` or any other GPG backed secret store. Is that something that you're:
1) Recommending?
2) Planning to incorporate?
3) Willing merge if PR came along?

The idea would be of course to not have to store the key in clear in a temp file and to have some integration with pass so that the UX is a simple GPG passphrase prompt when invoking `fscrypt unlock`.

**Comment by josephlr** [comment]
@obadz we haven't recently given a lot of thought to the `raw_key` protector types, as opposed to the login passphrase (`pam_passphrase`) or a normal password (`custom_passphrase`).

Ideally there wouldn't be gpg specific code in fscrypt. I (at least) would prefer a nice way to compose fscrypt with other key management tools. Something like:
```bash
# Setting up encryption
pass Encryption/Private | fscrypt encrypt ~/private --source=raw_key --name="pass key" 
# Unlocking later
pass Encryption/Private | fscrypt unlock ~/private
```
However, right now raw keys cannot be passed in via stdin. Instead a `--key=<file>` flag has to be passed in. I opened up #123 to address this shortcoming.

If it turns out that this fix makes fscrypt work well with gpg/pass, then we can discuss recommendations for potential user setups (perhaps on a Wiki page).
