### ISSUE TITLE
Consider removing `--key` argument from the CLI

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#123]
In #121, it was mentioned that composing various key management tools with fscrypt is a bit tricky at the moment. I would be easier if we simply ditched the `--key` argument and always just passed keys in via stdin.

Users can still do things like:
```bash
fscrypt unlock ~/private < secret.key
```
but it also allows composition like:
```bash
pass Encryption/Private | fscrypt unlock ~/private
```
As this is an (obviously) breaking change, it would need to come with a 0.3.0 release.

**Comment by mhogomchungu** [comment]
There is a noticeable difference in time when "unlocking" using a passphrase and when using a file.

I always though the difference is because a passphrase first goes through some sort of a key derivation function and the keyfile is used "as it" because it is assumed to be already processed.

Because of the above, it should be possible or appropriate to simply take contents of a file as pass them on a passphrase.

Latest version of SiriKali supports using fscrypt folders with a keyfile.

![Screenshot_20200603_155951](https://user-images.githubusercontent.com/3496115/83639700-bdc8bd80-a5b3-11ea-87da-80c30343bb31.png)

![Screenshot_20200603_160037](https://user-images.githubusercontent.com/3496115/83639713-c3be9e80-a5b3-11ea-8cff-d38c2e4aad5b.png)

**Comment by ebiggers** [comment]
@mhogomchungu, your observations are orthogonal to this suggested enhancement.  Requiring the key on stdin rather than `--key` wouldn't remove support for key files; the user would just need to pipe in the contents of the file.

Also, you do understand that the key file needs to be properly protected (e.g. not stored on the same disk as the corresponding encrypted directories), right?  The raw key support is meant for advanced use cases, such as downloading a key from another computer into tmpfs.  Are you sure it's appropriate to expose this functionality in your tool?

**Comment by bodograumann** [comment]
You should rephrase the ticket, because currently it is *not possible* to pass in the raw key via stdin.
(Cf. https://github.com/google/fscrypt/issues/121#issuecomment-455930238)
I would very much like to see this feature, to avoid creating a temporary file.

**Comment by blackham** [comment]
I would also LOVE to see the ability to pass the key via pipes (stdin). This is to avoid having the key touch disk. This also means setting up an encrypted folder (fscrypt encrypt xxxx) would need to accept all the options via command line options. 

Running a tool to pull the key from an external server, then saving that key to a tmp_fs, then making sure the "file" is deleted ... it's messy and un-UNIX like. 

Maybe something like this...
`/root/bin/get_key | fscrypt encrypt docker --user=root -use-stdin-key --protector=docker_dir `
