### ISSUE TITLE
linx kernel 4.9.103  vs 4.19.12

### ISSUE THREAD

**Issue by limbo127** [google/fscrypt#127]
hello, 
i'm using same .config linux kernel as base, from 4.9.103 --> 4.19.12. 
Now when i 'm trying fscypt status 
ffscrypt status
filesystems supporting encryption: 0
filesystems with fscrypt metadata: 0

MOUNTPOINT  DEVICE     FILESYSTEM  ENCRYPTION   FSCRYPT
/data       /dev/sda3  f2fs        not enabled  No

before [cbx-126-s028-f1fd581d-14c1-f588-6e5d-f44d3067f8a7]fscrypt status
filesystems supporting encryption: 1
filesystems with fscrypt metadata: 0

MOUNTPOINT  DEVICE     FILESYSTEM  ENCRYPTION  FSCRYPT
/data       /dev/sda3  f2fs        supported   No

what i miss ?   kernel encrypt on f2fs and ext4 are enables in config.
regards, 
Nicolas Prochazka

**Comment by ebiggers** [comment]
Probably your f2fs filesystem wasn't formatted with `-O encrypt`.  This feature flag was always supposed to be required to use encryption, but due to a f2fs bug it wasn't checked.  This was fixed in v4.15 by the commit [f2fs: deny accessing encryption policy if encryption is off](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ead710b7d82dc9e8184e10871c155a3ed8b3f673).  You can enable the `encrypt` feature on an existing f2fs filesystem by running `fsck.f2fs -O encrypt $device` with f2fs-tools v1.12.0 or later.  Or  when formatting, use `mkfs.f2fs -O encrypt $device`.

**Comment by limbo127** [comment]
thank for this information
Regards,
Nicolas
