### ISSUE TITLE
Support of Trim command on SSDs

### ISSUE THREAD

**Issue by wland32** [google/fscrypt#139]
How does fscrypt deal with the Trim command on SSDs?
Is Trimm supported?

dm-crypt has this feature but it is deactivated by default due to information leakage created by forwarding some usage information to the firmware that are needed for trim.

In case of fscript this might be differnet as it is another layer.

So how does fscript deal with SSDs and the Trim command?

**Comment by ebiggers** [comment]
TRIM will work as usual.  By itself, fscrypt is file encryption only, so the "information leakage" that TRIM would cause (the mapping of which blocks are free and which may be still in-use) is already there.  It's assumed that users of file encryption by itself don't care much about some filesystem metadata, otherwise they would use full-disk encryption instead.

**Comment by josephlr** [comment]
Closing as @ebiggers comment is correct. @wland32 feel free to reopen if you have other questions. The fscrypt kernel component does not deal with block devices (including SSD TRIM) directly. If you are concerned about metadata leaks, full disk encryption is the right approach.
