### ISSUE TITLE
Lock filesystem

### ISSUE THREAD

**Issue by varrel1337** [google/fscrypt#156]
Running 'fscrypt unlock DIRECTORY' will make the files in that directory available.
However, how do I "lock" that directory again? Currently the only way to do this seems to be a reboot of the system.

**Comment by ebiggers** [comment]
You can use `fscrypt purge`, but it operates on a whole filesystem rather than an individual directory,  it requires root, and it won't tell you whether any files couldn't be locked due to still being open.  https://github.com/google/fscrypt/pull/148 will add an `fscrypt lock` command that works properly.

**Comment by varrel1337** [comment]
Nice, thanks for the info
