### ISSUE TITLE
Auto-generate recovery passphrase when protector is on a different filesystem

### ISSUE THREAD

**Issue by Redsandro** [google/fscrypt#164]
@ebiggers [commented](https://github.com/google/fscrypt/issues/115#issuecomment-553059348):
> Login protectors are stored in the `/.fscrypt` directory on the __root filesystem.__ If that directory has been lost, then it's impossible to decrypt any directories that were protected by the login passphrase

Would it make sense to put this on the root of the __partition (device) that holds the encrypted directory__ in stead? If you have three drives with encrypted directories, and only the one that contains root file system breaks, it would mean data on _all_ drives is lost, not just the root drive that didn't even use encryption itself.

This actually happened to me on the [aforementioned](https://github.com/google/fscrypt/issues/115#issuecomment-553046403) computer. The SSD holding the root filesystem was from 2014 (5 years old). I do backup most of my files, but I do _not_ backup the root file system because I figure free software is already backed up on many crazy fast repositories (For example, I'm lucky to have gigabit internet and my ISP hosts a mirror of many repositories.) and software _configurations_ are stored in my home, which is backed up.

It's slightly frustrating to have two disks of data that I can't recover because some tiny metadata is not stored on the same device as the data that depends on it.

---

When part of my data - for example my `/home` directory - is on a separate partition, I already need to `fscrypt setup /home.` Now there is a `.fscrypt` directory on the root of both my `/` and my `/home/` partition.

I don't know how this works technically so I can only make assumptions here. But the `/.fscrypt` contains a `protector`, and the `/home/.fscrypt` contains a `protector.link`. If somehow the partition that contains the encrypted data links to the partition containing the protector, I am wondering if these could be reversed. Or let every partition that is set up for fscrypt keep their own copy of the protector. So that a perfectly healthy drive will never have to suffer data loss through the failure of a different drive.

**Comment by ebiggers** [comment]
There are several disadvantages to doing this:

- If a user has N login protectors rather than 1, it would take N times longer for them to log in (assuming that the password hashing isn't made less secure to compensate).
- If the user changes their login passphrase and some filesystems on which they have login protectors are not currently mounted, then those login protectors wouldn't be updated.  So those directories would stop being auto-unlocked, as they would still be protected by the old passphrase.
- If you lose an external drive which had a directory protected by a login protector, then an attacker would be able to recover the data by brute-forcing your login passphrase given the external drive only.  If the login protector is instead only stored on the system itself (as is currently the case), then the data will be unrecoverable to the attacker even if your login passphrase is weak.

So that's why the login protectors work as-is currently.

Did you consider just assigning a custom passphrase in addition to the login protector?  Custom passphrase protectors are always stored on the filesystem itself.  If you treat it just as a recovery passphrase (i.e., one you aren't typing all the time) and store it somewhere securely, it could be much stronger than your login passphrase.

**Comment by Redsandro** [comment]
Thank you for clarifying. The third one is pushing it, as the same is true for the de facto usage scenario where the encrypted home is on the same partition or hardware as the root file system, but the first two points make sense.

> Did you consider just assigning a custom passphrase __in addition to__ the login protector?

I did not, for two important reasons:

1. I assumed the device contained all the metadata necessary to recover files independent from the root filesystem. This assumption is strengthened because:
    * I have to explicitly run `fscrypt setup` on the partition that contains the to-be-encrypted directories, giving me the impression metadata is stored there;
    * The `fscrypt setup` command does not tell me what is happening or warn me about this risk.
2. I assumed I had to _pick one_ type of protector, and pam_passphrase is the most practical. The CLI output is ambiguous:
    *  > Your data can be protected with __one__ of the following sources:
        > 1 - pam_passphrase   
        > 2 - custom_passphrase
        > 3 - raw_key

So, yes, I will surely do this now. Perhaps then adding some measures to protect against the sort of misassumptions I have made would be beneficial. Here are some ideas:

1. Rephrase _"... can be protected with one __or more__ of the following ..."_
1. When choosing 1 (pam_passphrase), warn that the necessary protector is stored on the root filesystem and advise _or enforce_ that 2 or 3 is done in addition.
1. After choosing pam_passphrase, custom_passphrase could be run automatically immediately after, asking the user for a recovery passphrase.
    - When no password is entered, a long password could be auto-generated and stored in a `recovery_readme.txt` inside the directory that was just encrypted.
    - The path to `recovery_readme.txt` could be echoed back to the user. _"For important recovery instructions, see ..."_
    - If the encrypted directory contains a `Desktop` directory, place `recovery_readme.txt` in there.

**Comment by ebiggers** [comment]
> I did not, for two important reasons:
> 
> 1. I assumed the device contained all the metadata necessary to recover files independent from the root filesystem. This assumption was affirmed by:
>    
>    * I have to explicitly run `fscrypt setup` on the partition that contains the to-be-encrypted directories, giving me the impression metadata is stored there;
>    * The `fscrypt setup` command does not tell me what is happening or warn me about this risk.

I think this is outside the scope of `fscrypt setup`, since it doesn't know whether you're going to protect any directories with your login passphrase or not.  Also it's intentional that `fscrypt setup` always needs to be run, since the *policies* are always stored in `.fscrypt/policies` on the filesystem where the encrypted directories are.  It's only *protectors* that can be linked to a different filesystem.

> 2. I assumed I had to _pick one_ type of protector, and pam_passphrase is the most practical. The CLI output is ambiguous:
>    
>    * > Your data can be protected with **one** of the following sources:
>      > 1 - pam_passphrase
>      > 2 - custom_passphrase
>      > 3 - raw_key
> 
> So, yes, I will surely do this now. Perhaps then adding some measures to protect against the sort of misassumptions I have made would be beneficial. Here are some ideas:
> 
> 1. Rephrase _"... can be protected with one **or more** of the following ..."_

The immediate context of this is creating a single new protector, so "one or more" would be confusing too.  I think we should go with something like "The following protector sources are available:".

> 2. When choosing 1 (pam_passphrase), warn that the necessary protector is stored on the root filesystem and advise _or enforce_ that 2 or 3 is done in addition.
> 3. After choosing pam_passphrase, custom_passphrase could be run automatically immediately after, asking the user for a recovery passphrase.
>    
>    * When no password is entered, a long password could be auto-generated and stored in a `recovery_readme.txt` inside the directory that was just encrypted.
>    * The path to `recovery_readme.txt` could be echoed back to the user. _"For important recovery instructions, see ..."_
>    * If the encrypted directory contains a `Desktop` directory, place `recovery_readme.txt` in there.

I like the idea of generating a recovery passphrase and storing it in a .txt file in the encrypted directory for the user to do something with.  I'm not sure there's much value in allowing the user to choose the passphrase, though, as they will probably just re-enter their login passphrase, and then get confused when they get out-of-sync.  Instead I'm thinking that if the user chose a pam_passphrase protector *and* the directory is not on the root filesystem, `fscrypt encrypt` can just ask yes/no if the user wants a recovery passphrase, and if they answer yes, it automatically generates 12 characters in the set a-zA-Z0-9 and stores it in `encrypted_dir/fscrypt_recovery_readme.txt` along with some help text, and adds a custom passphrase protector with it.  (Note, the file can't actually be placed in `Desktop/`, since a newly encrypted directory is always empty.)

We could alternatively implement recovery codes (which has been planned for a long time); a recovery code would basically be the raw policy key as a 116-character base32 string.  It seems a recovery passphrase would be much more convenient though.

**Comment by Redsandro** [comment]
> I like the idea of generating a recovery passphrase and storing it in a .txt file in the encrypted directory for the user to do something with. 

Great. This seems to be the right mix of sensible and friendly.

> I'm not sure there's much value in allowing the user to choose the passphrase, though, as they will probably just re-enter their login passphrase (...)

I agree.

> `fscrypt encrypt` can just ask yes/no if the user wants a recovery passphrase

I think (some) people will underestimate the importance. I would not ask the question, but just do it. You can optionally add a command-line flag (e.g. `--skip-pam-recovery`) if you want to be able to skip this for reasons. Alternatively, if there are good reasons for not doing this, you should definitely append "(strongly recommended)" to the question.

> it [would] automatically generate(s) 12 characters in the set a-zA-Z0-9

Inspired on the third point of your first comment: I strongly recommend the autogenerated recovery passphrase to be 32 or more characters so that data will be harder to brute-force. As a paranoid person, I like to use 15+ character passwords, and it wouldn't feel right if the autogenerated recovery passphrase is shorter than that. People will copy this into their password manager anyway. There is no reason to keep it short.

> We could alternatively implement recovery codes (...). It seems a recovery passphrase would be much more convenient though.

I would put all my votes on the recovery passphrase. For ease of use, clarity and convenience.

**Comment by ebiggers** [comment]
It actually is helpful to keep it "short", as then it makes it much easier to e.g. physically write down.  The important thing is the *entropy* of the password, not its length per se.  12 random characters in `a-zA-Z0-9` has 71.4 bits of entropy, which is generally *much* more than what a user would come up with themselves even if they tried to make a much longer password.  And as the password is still hashed by Argon2 calibated to take 1 second on your computer (as it's designed for *much* weaker passwords), this is more than enough; it would take 1 billion computers like yours about 50000 years to brute force.

However, it might be a good idea to restrict the characters to a-z to eliminate any confusion, e.g. between o, O, and 0, in which case we could increase the length to 16 to compensate and get 75.2 bits of entropy.  FWIW, this is exactly how Google Application-Specific Passwords are generated.

**Comment by Redsandro** [comment]
> It actually is helpful to keep it "short", as then it makes it much easier to e.g. physically write down.

I've never met someone who physically wrote down a (recovery) password. Luckily the `ecryptfs` recovery passphrase was not easy to physically write down. I'd recommend against encouraging people to write their password down. Let them use their digital vault or password manager.

> FWIW, this is exactly how Google Application-Specific Passwords are generated.

Google Servers will rate-limit your auth requests. If I have your hardware, I can bruteforce directly. It's much faster. I don't think you can't have the same standards for file encryption as with a remove auth server. With encryption it's safe to assume the worst case scenario.

I recently read that 12 characters on 1 modern computer takes 2 centuries to crack, and it's getting shorter every year. That would mean renting a 400k botnet for 4 hours. You have to plan for the unexpected. Attackers are innovative. Although this is not the same, I remember this summer the NSA warned against the GoldBrute botnet, bruteforcing 1.5 million servers worldwide.

IIRC the US government went from recommending 56 bits in the '90s to 128 bit in the '00s to 256 bit in the '10s to 512 bit in the now for encryption algorhitms.

I might not understand encryption enough on a technical level to see how this is different, but let me put it another way: 

10 years ago Ubuntu/EcryptFS gave me a 16 character string as recovery passphrase. Now I'm expecting at least double that. Because I am technically unable to comprehend how only 12 characters can protect my confiscated hardware from being bruteforced by tyrannical governments, I would psychologically not trust this recovery protector, and therefor _remove_ it, and add a custom one with a longer password. In stead of saving me time, it now becomes a hurdle.

**Comment by ebiggers** [comment]
> > FWIW, this is exactly how Google Application-Specific Passwords are generated.
> 
> Google Servers will rate-limit your auth requests. If I have your hardware, I can bruteforce directly. It's much faster. I don't think you can't have the same standards for file encryption as with a remove auth server. With encryption it's safe to assume the worst case scenario.

Actually the standard assumption for website passwords is that the attacker has exfiltrated the database, so they can indeed bruteforce it offline.  That's why standard practice is to hash passwords and not store them in the database directly.

> I recently read that 12 characters on 1 modern computer takes 2 centuries to crack, and it's getting shorter every year. That would mean renting a 400k botnet for 4 hours. You have to plan for the unexpected. Attackers are innovative. Although this is not the same, I remember this summer the NSA warned against the GoldBrute botnet, bruteforcing 1.5 million servers worldwide.

That makes no sense --- that would mean that a single computer can check `((26+26+10)**12)/(200*365*24*3600)` = 511 billion passwords per second.

fscrypt uses a memory-hard password hashing function that's calibrated to take 1 second when using all your CPUs.  So it's over 500 billion times harder than you think it is.

> IIRC the US government went from recommending 56 bits in the '90s to 128 bit in the '00s to 256 bit in the '10s to 512 bit in the now for encryption algorhitms.
> 
> I might not understand encryption enough on a technical level to see how this is different, but let me put it another way:
> 
> 10 years ago Ubuntu/EcryptFS gave me a 16 character string as recovery passphrase. Now I'm expecting at least double that. Because I am technically unable to comprehend how only 12 characters can protect my confiscated hardware from being bruteforced by tyrannical governments, I would psychologically not trust this recovery protector, and therefor _remove_ it, and add a custom one with a longer password. In stead of saving me time, it now becomes a hurdle.

You seem to be misunderstanding the difference between a password and an encryption key.  Passwords are always understood to be low entropy; that's why the standard practice is to use a password hashing function that takes a lot of time to run.  fscrypt uses Argon2 which is state of the art and also requires a lot of memory to run and uses all CPUs.  We also set the default hashing time to 1 second which is very conservative compared to which is typically used for password hashing.

So a fscrypt password with e.g. 256 bits of entropy is not meaningfully more secure than 75 bits (though this is true for *raw encryption keys*).

FWIW, it's also false that 512 bit symmetric encryption keys are being recommended.  2^256 is already approximately the number of atoms in the observable universe.

I wish that people focused more on real-world attacks, like exploitation of software bugs, and not pretend security like using ludicrously large cryptographic margins :-(

That being said, we might just make the password super long anyway to avoid complaints like this, even though there's no technical reason.

**Comment by Redsandro** [comment]
I might have come off a bit strong, and I definitely lack certain understandings. My apologies. I am only one voice, please don't decide the password length policy on my voice alone.

> FWIW, it's also false that 512 bit symmetric encryption keys are being recommended.

You are right, I misremembered. AES-512 is being investigated for satellite communication. They had a hardware prototype in 2011. Someone is paranoid enough.

> 2^256 is already approximately the number of atoms in the observable universe.

I'll take your word for that!

I do recommend not going too short on a recovery passphrase, because there are folks in the linux community more paranoid than I, and fscrypt might have to deal with scrutiny based on misunderstandings. Traditionally a weakness/shortcut will eventually be found, so better be on the safe side.

**Comment by Maryse47** [comment]
> I do recommend not going too short on a recovery passphrase, because there are folks in the linux community more paranoid than I, and fscrypt might have to deal with scrutiny based on misunderstandings.

I strongly recommend not develop this software in answer to scrutiny based on misunderstandings. I also don't think giving recommendations for this project without understanding technical details of cryptography is appropriate. This discussion doesn't make sense if you don't post technical arguments rather than "paranoid folks in the linux community said".

**Comment by Redsandro** [comment]
> I also don't think giving recommendations for this project without understanding technical details of cryptography is appropriate.

I disagree. The lack of nontechnical points of view during development is what makes Linux such a ruthless experience in many ways.

A purist technical point of view like that is exactly why [FileZilla refused to add support for a Master Password for 10 years](https://trac.filezilla-project.org/ticket/2935). The result was that for ten years, on every update, software tracking websites featured criticism that overshadowed the changelog.

So the deal is this. You can go Method A, or Method B. There is no technical necessity to go either way, except only one of them has the added benefit of easing people's minds for being unnecessarily strong. Rejecting a free perk that benefits others but not you is ruthless.

**Comment by Maryse47** [comment]
Password strength or AES key size isn't about nontechnical point of view and this is what you were trying to argue about here. After Erick patiently debunked each of your arguments one by one you are still giving "recommendations" and base them on "fscrypt might have to deal with scrutiny based on misunderstandings". No project should be developed in accordance to some "paranoid" people misunderstanding about it.

It's perfectly ok to discuss UX among other things but having strong opinions about tech technical  and critical aspects like cryptography without having background in it is hubris.

**Comment by Redsandro** [comment]
@ebiggers commented:
> Did you consider just assigning a custom passphrase in addition to the login protector?

Revisiting this: Since mounting old hardware in a new system doesn't seem to play nice with fscrypt, I brought together the band one last time just to test this route.

![image](https://user-images.githubusercontent.com/1702193/69000751-db169280-08d4-11ea-9130-f9286a7b2d4d.png)

You can't run `fscrypt encrypt` on a directory that is not empty, or on a directory that is already encrypted with pam_passphrase:

1. Assigning a custom passphrase to a previously encrypted home:

```
# fscrypt encrypt redsandro --user=redsandro
fscrypt encrypt: redsandro: Not an empty directory

Encryption can only be setup on empty directories; files cannot be encrypted in-place. 
Instead, encrypt an empty directory, copy the files into that encrypted directory, and 
securely delete the original with "shred".
```

2. Assigning a custom passphrase to an empty directory _after_ first adding pam_passphrase:

```
# mkdir test
# fscrypt encrypt test --user=redsandro
Your data can be protected with one of the following sources:
1 - Your login passphrase (pam_passphrase)
2 - A custom passphrase (custom_passphrase)
3 - A raw 256-bit key (raw_key)
Enter the source number for the new protector [2 - custom_passphrase]: 1
Enter login passphrase for redsandro: 
"test" is now encrypted, unlocked, and ready for use.

# fscrypt encrypt test --user=redsandro
fscrypt encrypt: test: file or directory already encrypted
```

In order to add a protector _in addition to_ an existing protector, we need to use `fscrypt metadata` to add a protector, add a policy, and link the two.

Is it friendly to do this automatically? I.e. instead of exiting with the error _"directory already encrypted"_, ask _"Directory encrypted with [something]. Do you want to add an additional protector?"_ (and hide pam_passphrase if it's already used).

**Comment by ebiggers** [comment]
> The immediate context of this is creating a single new protector, so "one or more" would be confusing too. I think we should go with something like "The following protector sources are available:".

10bbfcbfe125e9c9568031328e372c01ff144fc9 made this change.

> I would put all my votes on the recovery passphrase. For ease of use, clarity and convenience. It has the added benefit of most of the work (i.e. custom_password) being done already.

I implemented recovery passphrase support in https://github.com/google/fscrypt/pull/167.  Not yet merged to master branch, but feel free to try it out.  I've renamed this issue to be for this feature.

> Perhaps this can be done automatically. I.e. instead of exiting with the error "directory already encrypted", ask "Directory encrypted with [something]. Do you want to add an additional protector?" and calculate automatically the partition root and the protector containing policy. (And hide pam_passphrase if it's already used).

Can you please file a new Github issue for this suggestion?

Thanks!
