### ISSUE TITLE
Protector no longer exists on linked filesystem

### ISSUE THREAD

**Issue by hulpor** [google/fscrypt#186]
When setting up fscrypt (current git version) I ran into several issues.

First when I run 'fscrypt encrypt /home' (home is a mountpoint/separate partition) I get the message

> generating recovery passphrase because protectors are on a differnet filesystem

But the protectors are on the same filesystem at /home/.fscrypt

The encrypt operation still seemed to work, as there was no error message.

But when I run 'fscrypt unlock /home/targetfolder' I get the message that the folder is not encrypted.

Running fscrypt status /home will show a protector for the target folder but also the message:

> protector no longer exists on linked filesystem

After setting everything up several times I installed the last release v0.2.5 and everything works fine out of the box.

Looks like the current git version is broken for this setup. Let me now if I can do anything to help find whats causing this.

**Comment by ebiggers** [comment]
Can you please provide the full commands you ran and their output, along with the contents of `/proc/self/mountinfo`?  Some of the things you wrote don't make sense; for example, `fscrypt encrypt /home` will actually always fail if `/home` is really the root directory of a filesystem.  Also, `fscrypt status /home` should only list policies and protectors; it shouldn't show any folder paths.  It would also be helpful to know which type of protector you're using.  If you're using a pam_passphrase protector, it's indeed expected that it's a linked protector and that a recovery passphrase is generated.

**Comment by hulpor** [comment]
The correct comamnd that I used was indeed 
> fscrypt encrypt /home/username


I will recreate the setup as soon as possible to get the correct error and full messages.

Meanwhile this https://github.com/google/fscrypt/issues/187 was also part of the error messages

**Comment by ebiggers** [comment]
Okay, I found how to reproduce this, so I don't think I need more information.

The main problem here is a duplicate of https://github.com/google/fscrypt/issues/187.  However there are two additional issues here:

* When `fscrypt encrypt` fails, the output is not clear in some cases.
* When `fscrypt encrypt` fails, newly-created linked protectors are not deleted.

**Comment by ebiggers** [comment]
Can you check whether https://github.com/google/fscrypt/pull/189 fixes this?  I'll try to improve handling of `fscrypt encrypt` failures too, but https://github.com/google/fscrypt/pull/189 will make `fscrypt encrypt` not fail in the first place.

**Comment by hulpor** [comment]
Since I reproduced it anyway, here is the result:
```

fscrypt setup
Create "/etc/fscrypt.conf"? [Y/n] 
Customizing passphrase hashing difficulty for this system...
Created global config file at "/etc/fscrypt.conf".
Metadata directories created at "/.fscrypt".


fscrypt setup /mnt/
Metadata directories created at "/mnt/.fscrypt".

fscrypt encrypt /mnt/test/ --user=tester
The following protector sources are available:
1 - Your login passphrase (pam_passphrase)
2 - A custom passphrase (custom_passphrase)
3 - A raw 256-bit key (raw_key)
Enter the source number for the new protector [2 - custom_passphrase]: 1
Enter login passphrase for tester: 
Generating recovery passphrase because protector is on a different filesystem.
fscrypt encrypt: login protectors do not need a name

fscrypt unlock /mnt/test
fscrypt unlock: get encryption policy /mnt/test: file or directory not encrypted

fscrypt status
filesystems supporting encryption: 1
filesystems with fscrypt metadata: 2

MOUNTPOINT  DEVICE          FILESYSTEM  ENCRYPTION     FSCRYPT
/           /dev/dm-1       ext4        not enabled    Yes
/boot       /dev/nvme0n1p2  ext2        not enabled    No
/boot/efi   /dev/nvme0n1p1  vfat        not supported  No
/mnt        /dev/sda1       ext4        supported      Yes


fscrypt status /mnt/
ext4 filesystem "/mnt" has 1 protector and 1 policy

PROTECTOR  LINKED  DESCRIPTION
                   [filesystem /mnt: protector c29c975ad8c735ad: no longer exists on linked filesystem]

POLICY            UNLOCKED  PROTECTORS
8e676538101b6192  No        c29c975ad8c735ad


Kernel version 5.4



cat /proc/self/mountinfo
22 29 0:20 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
23 29 0:5 / /proc rw,nosuid,nodev,noexec,relatime shared:15 - proc proc rw
24 29 0:6 / /dev rw,nosuid,noexec,relatime shared:2 - devtmpfs udev rw,size=8068884k,nr_inodes=2017221,mode=755
25 24 0:21 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
26 29 0:22 / /run rw,nosuid,nodev,noexec,relatime shared:5 - tmpfs tmpfs rw,size=1620780k,mode=755
29 1 254:1 / / rw,relatime shared:1 - ext4 /dev/mapper/dell--vg-root rw,errors=remount-ro
30 22 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
31 24 0:25 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
32 26 0:26 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
33 22 0:27 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
34 33 0:28 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:10 - cgroup2 cgroup2 rw,nsdelegate
35 33 0:29 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,xattr,name=systemd
36 22 0:30 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:12 - pstore pstore rw
37 22 0:31 / /sys/firmware/efi/efivars rw,nosuid,nodev,noexec,relatime shared:13 - efivarfs efivarfs rw
38 22 0:32 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:14 - bpf none rw,mode=700
39 33 0:33 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,devices
40 33 0:34 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,cpu,cpuacct
41 33 0:35 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,blkio
42 33 0:36 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,rdma
43 33 0:37 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,net_cls,net_prio
44 33 0:38 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,pids
45 33 0:39 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,cpuset
46 33 0:40 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,memory
47 33 0:41 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:24 - cgroup cgroup rw,perf_event
48 33 0:42 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:25 - cgroup cgroup rw,freezer
49 23 0:43 / /proc/sys/fs/binfmt_misc rw,relatime shared:26 - autofs systemd-1 rw,fd=27,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13843
50 24 0:19 / /dev/mqueue rw,nosuid,nodev,noexec,relatime shared:27 - mqueue mqueue rw
51 24 0:44 / /dev/hugepages rw,relatime shared:28 - hugetlbfs hugetlbfs rw,pagesize=2M
52 22 0:8 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime shared:29 - debugfs debugfs rw
114 29 259:2 / /boot rw,relatime shared:61 - ext2 /dev/nvme0n1p2 rw
117 114 259:1 / /boot/efi rw,relatime shared:63 - vfat /dev/nvme0n1p1 rw,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro
120 49 0:45 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime shared:65 - binfmt_misc binfmt_misc rw
647 26 0:48 / /run/user/133 rw,nosuid,nodev,relatime shared:359 - tmpfs tmpfs rw,size=1620776k,mode=700,uid=133,gid=141
411 26 0:47 / /run/user/1000 rw,nosuid,nodev,relatime shared:222 - tmpfs tmpfs rw,size=1620776k,mode=700,uid=1000,gid=1000
431 411 0:49 / /run/user/1000/doc rw,nosuid,nodev,relatime shared:233 - fuse /dev/fuse rw,user_id=1000,group_id=1000
451 22 0:50 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime shared:244 - fusectl fusectl rw
727 29 8:1 / /mnt rw,relatime shared:401 - ext4 /dev/sda1 rw



When using a custom passphrase:

 fscrypt encrypt /mnt/test/ --user=tester
Should we create a new protector? [y/N] y
The following protector sources are available:
1 - Your login passphrase (pam_passphrase)
2 - A custom passphrase (custom_passphrase)
3 - A raw 256-bit key (raw_key)
Enter the source number for the new protector [2 - custom_passphrase]: 
Enter a name for the new protector: test
Enter custom passphrase for protector "test": 
Confirm passphrase: 
"/mnt/test/" is now encrypted, unlocked, and ready for use.


fscrypt status /mnt/
ext4 filesystem "/mnt" has 2 protectors and 2 policies

PROTECTOR         LINKED  DESCRIPTION
                          [filesystem /mnt: protector c29c975ad8c735ad: no longer exists on linked filesystem]
37a0cf6d809a6d67  No      custom protector "test"

POLICY            UNLOCKED  PROTECTORS
8e676538101b6192  No        c29c975ad8c735ad
c730b107ae5961d1  Yes       37a0cf6d809a6d67    


fscrypt lock /mnt/test --user=tester
Encrypted data removed from filesystem cache.
"/mnt/test" is now locked.


fscrypt unlock /mnt/test --user=tester
Enter custom passphrase for protector "test": 
"/mnt/test" is now unlocked and ready for use.
```

**Comment by hulpor** [comment]
> Can you check whether #189 fixes this? I'll try to improve handling of `fscrypt encrypt` failures too, but #189 will make `fscrypt encrypt` not fail in the first place.

Yes, with this commit the error disappears.


```
fscrypt encrypt /mnt/test --user=tester
The following protector sources are available:
1 - Your login passphrase (pam_passphrase)
2 - A custom passphrase (custom_passphrase)
3 - A raw 256-bit key (raw_key)
Enter the source number for the new protector [2 - custom_passphrase]: 1
Enter login passphrase for tester: 
Generating recovery passphrase because protector is on a different filesystem.
See "/mnt/test/fscrypt_recovery_readme.txt" for important recovery instructions!
"/mnt/test" is now encrypted, unlocked, and ready for use.

fscrypt status /mnt/test
"/mnt/test" is encrypted with fscrypt.

Policy:   eb82f5af0bd1fc72
Options:  padding:32 contents:AES_256_XTS filenames:AES_256_CTS policy_version:1 
Unlocked: Yes

Protected with 2 protectors:
PROTECTOR         LINKED   DESCRIPTION
95700a7e285e5b16  Yes (/)  login protector for tester
9719ec3604d78d8e  No       custom protector "Recovery passphrase for test"

fscrypt unlock test --user=tester
The available protectors are: 
0 - login protector for tester (linked protector on "/")
1 - custom protector "Recovery passphrase for test"
Enter the number of protector to use: 0
Enter login passphrase for tester: 
"test" is now unlocked and ready for use
```
However I am kinda confused about this recovery Protector. Why was this created, how do I disable/remove it? I don't want any secondary passphrase to my key.

Also, having to choose which protector to use is kinda annoying as well.
An option to disable this recovery stuff would be nice.

I know this is a development version, Just providing my thoughts.

**Comment by ebiggers** [comment]
See https://github.com/google/fscrypt/issues/164 and also `/mnt/test/fscrypt_recovery_readme.txt` (like the command suggested) for more information about the recovery passphrase.

If you don't want the recovery passphrase, you can just ignore it.  It has 94 bits of entropy, so it's orders of magnitude more secure than your login passphrase.

But we're in a tough spot if people are going to complain when a recovery passphrase is generated, **and** also complain if they lose their data because no recovery passphrase was generated.  It's very difficult to make every happy.

Maybe the best compromise is to make it a y/n prompt, with default y if the protector is on a different filesystem and default n otherwise.

**Comment by ebiggers** [comment]
In https://github.com/google/fscrypt/pull/193 I've proposed to make it ask:

`Protector is on a different filesystem! Generate a recovery passphrase (recommended)? [Y/n]`

It's `y` by default, but it will only ask if the protector is located on a different filesystem and the option `--no-recovery` was not given.  Otherwise, there is no prompt and no recovery passphrase is generated.

**Comment by ebiggers** [comment]
I've merged https://github.com/google/fscrypt/pull/189 which fixes the main bug here.

I've also opened pull requests to address the other issues raised here:

https://github.com/google/fscrypt/pull/191 to make it clear that the error messages are actually errors.
https://github.com/google/fscrypt/pull/192 to ensure that `fscrypt encrypt` cleans up properly on error.
https://github.com/google/fscrypt/pull/193 to allow disabling the recovery passphrase.

**Comment by ebiggers** [comment]
All the pull requests mentioned in https://github.com/google/fscrypt/issues/186#issuecomment-579065703 have been merged.  So everything reported in this issue should be fixed now.

**Comment by hulpor** [comment]
> If you don't want the recovery passphrase, you can just ignore it. It has 94 bits of entropy, so it's orders of magnitude more secure than your login passphrase.

While I agree that 94 entropy is more then most login passphrases, isn't this still an issue?
Many (high) security guides recommend using a strong passphrase that in itself (without considering hashing) has the same or higher entropy as the key. Having a passphrase of 20 (128 bit) or even more then 40 (256 bit) characters would guarantee that, even with the hashing algorithms broken, the security will now drop below the security guarantee of the encryption keys entropy.
Since fscrypt uses 256 bit AES keys, wouldn't that mean that an automatically generated recovery key should be at least 256 bit entropy?

In theory having only 94 bit entropy could be considered a vulnerability if the user chooses e.g. a 40 character random login passphrase, since the security of the users passphrase is higher then the one of the recovery key. The security will be lower then the user expected.
Granted this is a rare case but still possible.

If there is a reason to keep the recovery passphrase short, I would recommend at least 128 bit entropy.
Am I overlooking something?

**Comment by ebiggers** [comment]
It's a recovery *passphrase*, not a recovery key.  It still goes through the Argon2 passphrase hashing, which is designed for low entropy passphrases, and is already way overkill for a 94-bit entropy passphrase.  Looking at the numbers: fscrypt calibrates the Argon2 passphrase hashing to take 1 second, use all your CPUs, and use lots of memory.  So even if an attacker had 1 trillion computers like yours, it still would take them 632 million years to try all passphrases with 94 bits of entropy (20 characters a-z).

And yes, it's important to keep the passphrases a sane length for usability reasons, and not make someone who is risking losing all their data save and enter a 55-character passphrase for no reason.

As for Argon2 being broken, in the real world there are many more much more likely things to worry about, like software bugs, or fscrypt not protecting filesystem metadata.  But if you really *did* want to not depend on Argon2 with fscrypt, then you'd actually have to use a raw_key protector rather than a login protector, in which case you wouldn't be prompted to generate a recovery passphrase anyway, and even if it did you could still say no if you wanted.

So I see no sane reason to further increase the length of the recovery passphrases.

**Comment by gerout7** [comment]
I have a related question regarding the hashing.

From my understanding, fscrypt (optinally) uses the login password and generates a hash using argon2. However, the same password is also available as a sha512 hash in /etc/shadow with only 5000 iterations by default, which makes this sha512 hash the by far weaker hash for the same password.

This means that for the login password, an attacker would target the sh512 hash and not the argon2 hash that fscrypt uses, since both hashes are generated from the same password and cracking one of those hashes is enough.

Is this assumption correct?

**Comment by ebiggers** [comment]
Yes that's correct.  That's a fundamental limitation of any encryption solution that uses your login passphrase to protect your data.  But for `fscrypt`, we could at least recommend that users either [increase the number of rounds in /etc/shadow](https://wiki.archlinux.org/index.php/SHA_password_hashes#Increasing_security), use a strong login passphrase, or use a custom passphrase protector instead of a login protector.  I filed https://github.com/google/fscrypt/issues/220 to track this so that it doesn't get lost.
