### ISSUE TITLE
reading or writing to unlocked encrypted directory causes "Required key not available" error

### ISSUE THREAD

**Issue by dr-bonez** [google/fscrypt#212]
platform: raspbian kernel 4.19.113-v8+
fscrypt version v0.2.7, compiled for linux armhf (32 bit)
workflow:
```
fscrypt setup
mkdir vault
fscrypt encrypt --user=root vault
cp test.txt vault/
cp: cannot create regular file 'vault/test.txt': Required key not available
```

**Comment by ebiggers** [comment]
Is this with policy version 2?  (Run `fscrypt status vault/`.)

**Comment by josephlr** [comment]
> Is this with policy version 2? (Run `fscrypt status vault/`.)

The kernel version seems too old for this to be a V2 policy. So it means there's a kernel keyring issue.

@dr-bonez what is the output of `keyctl show @s`? I also noted that you're using `fscrypt encrypt --user=root vault`, are you running these commands as a normal user or as root? What happens if you just do `fscrypt encrypt vault`?

**Comment by dr-bonez** [comment]
policy version is 1

Yes I am running as root. without the --user, I get: 
```[ERROR] fscrypt encrypt: user must be specified when run as root

When running this command as root, you usually still want to provision/remove keys for a normal user's keyring and use a
normal user's login passphrase as a protector (so the corresponding files will be accessible for that user). This can be
done with --user=USERNAME. To use the root user's keyring or passphrase, use --user=root.```

keyctl show @s returns:
```
Keyring
 584250072 --alswrv   1000  1000  keyring: _ses
 257791045 ---lswrv   1000 65534   \_ keyring: _uid.1000
```

**Comment by ebiggers** [comment]
You're using a shell that you elevated to root in using `sudo`, right?  I think it's "expected" that root's user keyring isn't used then, but rather only the original user's.  One solution is to use `--user=$SUDO_USER` instead of `--user=root`.

If you can upgrade to kernel v5.4 and use v2 policies instead, that would also avoid issues like this.

**Comment by dr-bonez** [comment]
I elevated to root using `sudo -i`. curious if it would be different if i used `sudo su`.

unfortunately raspbian hasn't upgraded to 5.4 yet, and I'm not sure how stable the raspberry pi will be on the actual linux kernel, instead of their fork.

**Comment by josephlr** [comment]
> I elevated to root using `sudo -i`. curious if it would be different if i used `sudo su`.

It would not be, the issue is that when you `sudo -i` or `sudo su` the normal user's keyring is still active (this is one of many bugs with the Linux Kernel Keyring, which we stopped using w/ V2 policies). So what happens is that when you run `sudo fscrypt encrypt --user=root vault` the key is placed in `root`'s keyring (which can be seen by running `sudo keyctl show @u`), but the active keyring still belongs to `$SUDO_USER` (which can be seen by running `sudo keyctl show @s`), making it appear that the directory is unlocked.

Here are the options to get around this:

1. Don't use the root user at all, and just unlock. For example:
    ```bash
    sudo fscrypt setup
    mkdir vault
    fscrypt encrypt vault
    ```
1. Login as the root user directly. This makes the root user's keyring active. Then `fscrypt encrypt --user=root valut` will work normally. However, this isn't really an option if you've disabled root login.

1. If `vault` needs to owned by root, just running `fscrypt encrypt vault` as a normal user will give "Permission Denied". However, you can setup the encryption as root, and then unlock it as the normal user. For example:
    ```bash
    sudo fscrypt encrypt vault --skip-unlock
    fscrypt unlock vault
    ```
1. If you absolutely must have the fscrypt key in the root keyring. You can run `sudo keyctl @u @s` to make root's user keyring active. This isn't ideal as it can cause security issues and the fix will only last for the duration of the session.

Let me know if any of these work for your usecase. Depending on what works the best, we will probably update the documentation. @ebiggers, any other options you can think of?

> unfortunately raspbian hasn't upgraded to 5.4 yet, and I'm not sure how stable the raspberry pi will be on the actual linux kernel, instead of their fork.

Ya, Raspbian is based on Debian stable, so you'll be waiting O(years) before there's a release with 5.4 or higher support. I think mainline Debian now supports the Rasberry Pi, but I can understand wanted to stick with the official distro.

**Comment by josephlr** [comment]
@ebiggers, I think we can make this easier to diagnose. When unlocking w/ the V1 user keyring, what should we do if the user keyring isn't in the session keyring?

Our options could be:
- Warn, saying that it won't work
- Fail, require the user to link the appropriate user keyring into the session keyring first

**Comment by dr-bonez** [comment]
Great, logging in directly as root fixed this. However, the next step for me was to get it working with docker, which looking at the other issues, it looks like that can't work without 5.4. I guess I have to look into either using the stock linux kernel, using an unstable raspbian kernel, or applying this patch to 4.19 somehow: https://patchwork.kernel.org/cover/10881911/.
Thanks for the help!
