### ISSUE TITLE
Integrate fscrypt in to Ubuntu 17.10 Artful

### ISSUE THREAD

**Issue by josephlr** [google/fscrypt#24]
Fscrypt is intended to replace [eCryptfs](https://wiki.archlinux.org/index.php/ECryptfs) as the implementation for home directory encryption in Ubuntu.

Tyler Hicks will be the main POC at Canonical

**Comment by tyhicks** [comment]
fscrypt didn't make the Ubuntu 17.10 release but it is in Bionic Beaver (Ubuntu 18.04 LTS):

  https://launchpad.net/ubuntu/+source/fscrypt/0.2.2-0ubuntu2

Only binary packages for amd64, i386, and arm64 are available. The package fails to build on armhf due to [test failures](https://launchpadlibrarian.net/343725170/buildlog_ubuntu-bionic-armhf.fscrypt_0.2.2-0ubuntu2_BUILDING.txt.gz). On ppc64el and s390x, the build failure is due to Bionic Beaver not having a new enough golang to support c-shared buildmode for the PAM module.

**Comment by tyhicks** [comment]
I am packaging the fscrypt utility in its own binary package (`fscrypt`) and the PAM module in a separate binary package (`libpam-fscrypt`) so I could skip the building of the `libpam-fscrypt` binary package on ppc64el and s390x until a new enough version of golang is available in Bionic.

**Comment by josephlr** [comment]
`fscrypt` is in Ubuntu 18.04, so this is resolved.
