### ISSUE TITLE
Can "unlock" be done without login?

### ISSUE THREAD

**Issue by animebing** [google/fscrypt#299]
I am running a service in ubuntu virtual machine using `virtualbox`, in order to protect the code and data, I use `fscrypt` to encrypt the code directory. I will deploy the service to others' computers and I don't hope they can login to have access to this directory, so I am trying to `unlock` the directory during boot without login using `root`, but it doesn't work until I login, which is really confusing me, so it is impossible or I have done something wrong or missed something, thank you.

My operating enviroments are

- ubuntu 18.04 with kernel 4.15 and no desktop
- fscrypt 0.2.0
- virtualbox 6.1.22

**Comment by ebiggers** [comment]
Unlocking directories as root and then accessing them by a normal user didn't work properly with directories that are encrypted using a v1 encryption policy.  This was all already fixed by v2 encryption policies; please see https://github.com/google/fscrypt#cant-log-in-with-ssh-even-when-users-encrypted-home-directory-is-unlocked for more information.  In order to re-create your directory with a v2 encryption policy you will need to upgrade to Linux kernel 5.4 or later and `fscrypt` 0.2.7 or later.

**Comment by ebiggers** [comment]
I've improved the documentation linked to above; the correct link is now https://github.com/google/fscrypt#some-processes-cant-access-unlocked-encrypted-files.

I think that answers your question, but feel free to re-open this if not.
