### ISSUE TITLE
Explain threat model and improve comparison with other encryption solutions

### ISSUE THREAD

**Issue by robszy** [google/fscrypt#318]
As fscrypt turned from user keyring to fskeyring and changed when it is usable as encryption (was also access control) solution in README in other encryption solutions section we should inform user that:

As fscrypt is not access control mechanism there are 2 ways of using it:

- true single user env so no one can stop by and add another user or modify system to copy out encrypted folder when you are logged in. 
  Of course in encrypted home case you need to be sure that all important data stays in home which could be hard in case of mistake.
  True single user could be also hard because you have to be sure that no one touched your PC e.g. booting from pendrive every time you open your encrypted dir.
  It will only help when you loose your PC/laptop because attacker will need to decipher home folder on his own.
  
  
- highly specialised multi user env with secure boot,rootless,read only filesystems,selinux hardened env like Android but it is beyond the reach of ordinary user.
  Plugging pendrive to boot from is hard and if it could be done whole system is encrypted
  Access control is good with selinux which cant be switched  off :)

Only real option of security for ordinary user is using whole disk encryption because no one would tamper with your disk and you won't make mistake copying out sensitive data from home so you are on save side

**Use fscrypt with caution as it is not intended to use for average multiuser linux distro with root access and selinux turned off.**

Line from other encryption solutions section:

> One example of a reasonable setup could involve using dm-crypt with a TPM or Secure boot key, while using fscrypt for the contents of a home directory. This would still encrypt the entire drive, but would also tie the encryption of a user's personal documents to their passphrase.

with assumption that user choose FDE using fscrypt is useless in single user env because fscrypt is only usable in single user case. So i would delete it. This is case of DE and CE in Androd which won't be used in standard linux case.

This line also suggest with setting of 0700 that fscrypt could be used in multi user env which is not true on standard desktop linux.
> Setting the mode of your encrypted directory to 0700 will prevent users other than the directory's owner and root from accessing it while it is unlocked. In fscrypt v0.2.5 and later, fscrypt encrypt sets this mode automatically.

So of course we could set 0700 but only one user could use PC with fscrypt used and will be reasonably secure as we can't hide from root and we cannot trust root user in general.
Only selinux can prevent root from doing something but this is out of scope in average distribution configuration.

**Comment by ebiggers** [comment]
The comparison between `fscrypt` and other encryption systems does need to be reworked, but most of your suggestions are just plain wrong.  Most of your complaint is that `fscrypt` (by itself) doesn't protect against [evil maid attacks](https://en.wikipedia.org/wiki/Evil_maid_attack), with an assumption that LUKS/dm-crypt (FDE) *would* protect against such attacks.  However, actually the way that LUKS/dm-crypt is used on Linux (outside of Chrome OS and Android) doesn't protect from such attacks either.  The author of `systemd` just posted a detailed blog post on this, which I'd highly recommend reading: http://0pointer.net/blog/authenticated-boot-and-disk-encryption-on-linux.html.  Fixing that issue (by implementing "Verified Boot") is largely orthogonal to what type of encryption you are using.

**Comment by robszy** [comment]
Thanks for link. Very helpful.

So to illustrate my view mind those 2 cases:

1. So say we have Chrome Os secure boot as you like and FDE  as one case

2. Second case is Chrome Os like secure boot and use only fscrypt to encrypt home dir leaving all other partitions in plain text.

Which is more secure 1 or 2 ?

Which will enable evil maid attacks ?

**Comment by ebiggers** [comment]
There is no single answer to that question as it depends on many things.  All else being equal, encrypting more is obviously better than encrypting less and thus the FDE version would be better, but there many other factors to consider such as:

* Whether the use of FDE implies a less well-protected key, as is often the case in practice for usability reasons or to support multiple users or profiles.  (If it's a true single user system and the user is a "power user" who cares a lot about encryption, this won't be the case as they will set a strong boot-time password.  But in practice that isn't the only case, as I've explained previously.)

* Where the executable code is stored and how it is authenticated, if at all.  Authentication could happen through partition-level hashes, e.g. dm-verity; file-level hashes, e.g. IMA appraisal or something based on fs-verity; or disk/file encryption, which isn't actually authenticated, but can be (ab)used as "poor man's authentication".  If the system relies on encryption as "poor-man's authentication" for executable code, then removing or not applying encryption to such files would be a problem.  However, if the system already uses a proper authentication mechanism for such files (as it should) then not encrypting those files wouldn't be a problem, as far as an offline attacker trying to change these files is concerned.

* How other on-disk data such as configuration files and filesystem metadata are authenticated, and whether the attacker is "advanced" enough to e.g. mount an attack using a zero-day memory unsafety bug in a Linux filesystem implementation to get code execution, vs. just modifying some code on-disk which is a much more straightforward attack.

Note that Chrome OS both implements Verified Boot and uses the kernel side of `fscrypt`.  If you have questions about Chrome OS security, they have some pretty detailed security model documents available.

**Comment by robszy** [comment]
Ok so adding if  Secure Boot is available to my issue will turn them plain right :)

So as we go deeper we could have problem with UEFI Firmware when someone find out how to replace it so physical security is of utmost importance of course without internet connected.

**Comment by robszy** [comment]
I've got one question:

Is AES-GCM  authenticated encryption ? As i see it is not supported in kernel.

**Comment by ebiggers** [comment]
Yes, AES-GCM is an authenticated encryption algorithm.  The kernel side of `fscrypt` doesn't support any authenticated encryption algorithms, due to the difficulty in dealing with ciphertext expansion.  The Linux kernel does contain implementations of some authenticated encryption algorithms including AES-GCM, but they are only used by other Linux kernel features such as VPN support.  LUKS/dm-crypt can use authenticated encryption, but only if it is set up on top of dm-integrity, which isn't too practical.

**Comment by robszy** [comment]
Is there a chance of implementing it in fscrypt because it would be in kernel side of fscrypt and it would be perfect for users that only need to encrypt disk and be sure of data safety (also it won't be poor man's authentication and cpus are more than capable).

With AES-GCM and pendrive  to boot that is never left unatended it would be pretty  good protection for  evil maid attacks in this days without TMP and SecureBoot.

**Comment by ebiggers** [comment]
It could be supported if the filesystem is located on top of a dm-integrity device, although it wouldn't be very practical due to the heavy performance cost of dm-integrity.

Also note that if you are trying to harden the system to such an extent that you are worried about attackers manipulating AES-XTS ciphertexts, you probably should be encrypting the whole disk (either by using dm-crypt + fscrypt, or dm-crypt by itself if applicable for your use case) so that the filesystem metadata is protected too.

**Comment by robszy** [comment]
But i would be convenient for fscrypt  users because it will be lightweight fast and solid solution for people who don't want to use dmcrypt which is slow as you've said and also for Android users which will use best possible encryption for their CE data. Also you've said that encryption is poor man's authentication so it would be elegant solution to implement GCM and enable users to utilize this great technology.

Today it seams other way around so kernel is better suited to lock down linux box than to protect users (Thats why Netflix pushed dm-verity ). But who can change it if not google enginners :)

**Comment by ebiggers** [comment]
> But i would be convenient for fscrypt users because it will be lightweight fast and solid solution for people who don't want to use dmcrypt which is slow as you've said 

To re-iterate, the use of dm-integrity comes with a heavy performance cost.  This is because it needs to use data journaling to maintain consistency; otherwise your filesystem will be corrupted on crashes and power cuts.  This is true regardless of what is being used on top of it (e.g. dm-crypt, fscrypt, both, or neither).

> But who can change it if not google enginners :)

The kernel side of `fscrypt` is upstream Linux kernel code; anyone is welcome to contribute.  I would be happy to consider patches that add authenticated encryption support via dm-integrity, if someone was interested in implementing it.  I don't currently plan to implement this feature myself, as it doesn't currently appear to be a very useful feature.  It can sound useful to crypto people ("_of course_ you should be using authenticated encryption"), but with a performance hit of 2-3x (very roughly) due to the write amplification and extra syncs required to maintain data consistency, no one will actually use it other than a few power users.  One possibility is to support it only on F2FS in LFS-only mode instead of requiring dm-integrity, but that would be a pretty significant limitation.  Another possibility would be to support it on BTRFS if/when it adds encryption support.  Of course there is still the question of how much authenticated encryption of file contents matters if filesystem metadata isn't being authenticated too.

**Comment by robszy** [comment]
> To re-iterate, the use of dm-integrity comes with a heavy performance cost

zfs on linux implements GCM with hundreds of mb/s throughput

**Comment by ebiggers** [comment]
Yes, because ZFS is a copy-on-write filesystem.  Traditional filesystems which overwrite blocks in-place require dm-integrity.  Hence my mention of how dm-integrity would not be required in the cases of F2FS in LFS-only mode or BTRFS.  However as-is almost all users of the kernel side of `fscrypt` use either ext4, or F2FS in the default mode, which would both require dm-integrity in order to support authenticated encryption.  You are not the first person to think about this; this is something people have been trying to solve for years/decades.  It's been learned that a practical solution requires either hardware that natively supports per-block metadata (ideal), or the use of a nontraditional filesystem (less ideal as authenticating filesystem metadata properly can be hard, but filesystems can be designed to do it well).

**Comment by robszy** [comment]
So ubuntu users have such fine fs at their fingertips ie zfs with GCM to protect their privacy with planet level strength and no none use it. It is shocking. That needs to be pointed out in other encryption solutions.

With pendrive and zfs encrypted volume it would be pretty good encryption; actually planet level hard to crack :)

**Comment by awnumar** [comment]
> It could be supported if the filesystem is located on top of a dm-integrity device, although it wouldn't be very practical due to the heavy performance cost of dm-integrity.

As far as I know dm-integrity does not provide cryptographic assurances? It can't be compared to an authenticated encryption mode.

**Comment by robszy** [comment]
Can you add to other solutions in zfs that ubuntu have it and it is easly available in this dirto ?

In my opinion it should be drafted why this solution was developed as it will draw clear view how to use it (rootless android, se enforced, fully automated env)

Also when you say that it is good case for multiuser it should be stated explicitly that this is not solution for protecting date from other users confidential data, especially root which have all the power to do that unless SE is active which is rare  and we strongly discourage that sort of usage, I know that it is stated in Threat Model but it is very easy to think of it as access control which is wrong assumption (maybe locking shouldn't be even available as option to emphasize it?)

In single user case I would add that it would be hard to not copyout some encrypted data to filesystem less protected in not fully automated env like android.

Also in Threat model add that access control doesn;t work when you;re root unless SE which is very complicated and not used by most linux desktops and we trying to replace fsCrypt as in my understanding with this solution.
