### ISSUE TITLE
Guidance on upgrading fscrypt

### ISSUE THREAD

**Issue by talha-opteran** [google/fscrypt#320]
I need to upgrade fscrypt from `v.0.2.5` to `0.2.7` or above as per the [instructions](https://github.com/google/fscrypt#some-processes-cant-access-unlocked-encrypted-files) for working with Docker and encrypted folders. 

I'm wondering how I would go about doing this correctly. I installed the current version using:
`sudo apt-get install fscrypt libpam-fscrypt`

It's currently being used to encrypt the `home` folder. 

Some questions that I have:

1. Do I need to uninstall this version to upgrade from source or just overwrite?
2. Do I need to take any precautions? 
3. What about related configuration files?
4. I take it I need to reencrypt the `home` folder?

My current environment:
Ubuntu 20.04
5.11.0-34-generic
fscrypt: 0.2.5

**Comment by ebiggers** [comment]
> 1. Do I need to uninstall this version to upgrade from source or just overwrite?

If installing from source, you should uninstall your distro's version first.

> 2. Do I need to take any precautions?

If you're relying on `pam_fscrypt` unlocking your home directory at login, it could be a good idea to also allow logging in using an alternate account (which could be `root`) that doesn't rely on that, so that you can manually unlock your home directory if you mess up the PAM configuration.

> 3. What about related configuration files?

You will need to update your PAM configuration [as described in the README](https://github.com/google/fscrypt#enabling-the-pam-module-on-debian-or-ubuntu).

> 4. I take it I need to reencrypt the home folder?

If you want to upgrade to v2 encryption policies and not just upgrade your version of `fscrypt`, then yes you'll need to reencrypt your home directory [as described in the README](https://github.com/google/fscrypt#some-processes-cant-access-unlocked-encrypted-files).

**Comment by talha-opteran** [comment]
Thanks for the quick response. 

> If installing from source, you should uninstall your distro's version first.

I assume this removes the encryption as well as any configuration files? Do I need to uninstall `libpam-fscrypt` as well?

> If you're relying on pam_fscrypt unlocking your home directory at login ...

Not certain but I might be. I followed this [tutorial](https://tlbdk.github.io/ubuntu/2018/10/22/fscrypt.html) when installing it the first time and it installed and set up `libpam-fscrypt`. 
 
I'm a novice when it comes to this so want to make sure I have the steps right:

1. Uninstall `fscrypt` & `libpam-fscrypt`: `sudo apt remove fscrypt libpam-fscrypt && apt autoclean && sudo apt autoremove`
2. Install `fscrypt` from source
3. Update PAM configuration
4. Reencrypt the home directory

**Comment by ebiggers** [comment]
You should uninstall `libpam-fscrypt` too.  No, this won't decrypt your files; it just removes the packages needed to unlock them.

Whether `/etc/fscrypt.conf` is removed depends on your distro's policy for when configuration files for uninstalled packages are kept.  Either way, unless you changed settings in it that you want preserved, it doesn't matter.

If you aren't manually running `fscrypt unlock`, then yes you are using `pam_fscrypt`; that's the only other way to unlock encrypted directories.

Those steps sound fine.
