### ISSUE TITLE
Automatically clear cache when fscrypt purge is used

### ISSUE THREAD

**Issue by fancytenseletters** [google/fscrypt#35]
As described in https://github.com/google/fscrypt#i-can-still-see-files-or-filenames-after-running-fscrypt-purge-mountpoint encryption keys are still available in kernel cache after issuing `fscrypt purge` command.

There is however option to clear kernel cache by changing  `/proc/sys/vm/drop_caches` value to `2` or `3`. That means ` fscrypt purge` could send something like `sync && echo 3 > /proc/sys/vm/drop_caches` and the cache will be cleared. The downside is that ` fscrypt purge` would need execution with `sudo`.

**Comment by josephlr** [comment]
Thanks for pointing this out. If you look at #25, we have an option in the pam module to `echo 3 > /proc/sys/vm/drop_caches` so that closing a session has the desired effect. We should probably add some sort of `-f` flag that will do this an thus only work with `sudo`.

As a side note, we should be doing `echo 2 > /proc/sys/vm/drop_caches` as dropping the dentries and inodes should be enough without also dropping the whole page cache.
