### ISSUE TITLE
Can not move files/directories from unencrypted directory to encrypted directory

### ISSUE THREAD

**Issue by ilius** [google/fscrypt#76]
Here is my encrypted directory status:

	$ fscrypt status /home/ilius/test
	"/home/ilius/test" is encrypted with fscrypt.

	Policy:   44f05ee076fff2d7
	Unlocked: Yes

	Protected with 1 protector:
	PROTECTOR         LINKED  DESCRIPTION
	99db526fab54e494  No      custom protector "test"
	fscrypt$ fscrypt unlock /home/ilius/test
	fscrypt unlock: /home/ilius/test: this file or directory is already unlocked

And here is the error I get when I try to move a file from a normal (unencrypted) directory to my encrypted directory:

	mv: cannot move '../test.txt' to './test.txt': Operation not permitted

Also graphically (with Caja file manager) I get "Error moving file: Operation not permitted".

Copy works, both graphically and command line.
Also deleting the original file works (with the same user)

OS: Linux Mint 18.1 Serena
Kernel: Linux 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Tested with latest fscrypt (commit cedbe0e)

**Comment by fancytenseletters** [comment]
Moving unencrypted files (`mv`) to encrypted folder within same partition will fail, see https://wiki.archlinux.org/index.php/Ext4#Using_file-based_encryption. You have to copy them (`cp`) instead.

**Comment by ilius** [comment]
@fancytenseletters OK I understand now, thank you.

**Comment by tlbdk** [comment]
As a side node to this issue when other people end up here:

The reason mv fails it's because EPERM is returned instead of EXDEV that would be normal when the operation can not complete because of crossing a mount point or in this case moving an unencrypted file to an encrypted folder.

One could argue that the kernel interface is broken as most tools will only fall back to copy when they get an EXDEV, there seem to be some patches in the works but I'm not sure it the right location or if they will go upstream:

https://patchwork.kernel.org/patch/9943001/

**Comment by tlbdk** [comment]
@ebiggers Thanks for the answer and I understand the concern but this behavior very much depends on the partition setup, fx the reason I ran into to this issue is that Firefox has a bad habit of writing files to the /tmp folder and doing a rename from there to the home folder. If I had /tmp on it's own partition it would get EXDEV and fall back to copy and work without issue. The same goes for any "rename" from another partition(USB sticks, etc) here you will get EXDEV.

As I security feature it's not really the best way to tell the user about this issue as a lot of setups and use-cases will never get the EPERM even though it's the same issue.

Would it be possible to at least add the EXDEV behavior as a flag when mounting or when creating the fscrypt folder?

**Comment by tlbdk** [comment]
I'm my setup would it be possible to encrypt /tmp with a random key so I would not get the EPERM?

**Comment by josephlr** [comment]
@tlbdk thanks for bringing this issue up. @ebiggers is correct about the security concerns; however, if a bunch of tools are breaking as a result of this API choice, then we really should consider changing the kernel's behavior. The [justification in Mike's patchset](https://patchwork.ozlabs.org/cover/811270/
) is quite similar to the bug here.

There's also an inconsistency (in my opinion) about when `EPERM` vs `EXDEV` is returned:

|[`rename`](http://man7.org/linux/man-pages/man2/rename.2.html) operation | Current behavior  | Mike's proposed change |
|---|---|---|
| encrypted -> unencrypted (same filesystem) | `EPERM`  | `EXDEV` |
| encrypted -> unencrypted (different filesystem) | `EXDEV` | `EXDEV` |
| encrypted -> encrypted (same policy) | Success | Success  |
| encrypted -> encrypted (same protector) | `EPERM`  | `EXDEV` |
| encrypted -> encrypted (different policy/protector) | `EPERM`  | `EXDEV` |

Note that the kernel does not know the difference between the last two senarios, but this is still confusing for users of fscrypt. Also @tlbdk, this means that just encrypting `/tmp` with a dummy key will not fix your problems.

I'm reopening this bug as a documentation issue. However, I'll talk to Mike and Eric and see what they think about changing the kernel's API.

**Comment by josephlr** [comment]
It looks like github won't let me reopen this issue, see #124 for continued discussion.

**Comment by josephlr** [comment]
@tlbdk something that would resolve your current Firefox related issues would be to just have your `/tmp` be a tmpfs instead of a disk-based setup (I think this is the default on debian/redhat/arch based systems). Thanks to Eric for reminding me of this.

**Comment by tlbdk** [comment]
@josephlr Thanks, I ended up doing a bind mount from another folder, that seems to have the same effect.
